export interface Product {
  id: string;
  name: string;
  category: string;
  shortDescription: string;
  description: string;
  ingredients: string[];
  benefits: string[];
  usage: string;
  image: string;
  disclaimer?: string;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: "cosmetics",
    name: "Cosmetics",
    description: "Premium herbal cosmetics and personal care products",
    icon: "sparkles",
  },
  {
    id: "syrups",
    name: "Syrups",
    description: "Ayurvedic health syrups and liquid formulations",
    icon: "droplet",
  },
  {
    id: "herbs",
    name: "Herbs",
    description: "Premium quality dried herbs and botanicals",
    icon: "leaf",
  },
  {
    id: "oils",
    name: "Oils",
    description: "Traditional Ayurvedic oils for therapeutic use",
    icon: "droplet",
  },
  {
    id: "powders",
    name: "Powders",
    description: "Finely ground herbal powders and churnas",
    icon: "sparkles",
  },
  {
    id: "capsules",
    name: "Capsules",
    description: "Standardized herbal extracts in capsule form",
    icon: "pill",
  },
  {
    id: "formulations",
    name: "Formulations",
    description: "Classical Ayurvedic compound formulations",
    icon: "flask",
  },
];

export const products: Product[] = [
  {
    id: "kash-mukti",
    name: "KAS MUKTI – Herbal Cough Syrup",
    category: "syrups",
    shortDescription: "Traditional Ayurvedic Respiratory Support",
    description: "KAS MUKTI is a carefully crafted Ayurvedic herbal cough syrup formulated with a blend of time-tested herbs traditionally used to support respiratory wellness. Combining soothing botanicals, natural expectorants, and aromatic herbs, it helps promote respiratory comfort, maintain healthy airways, and support overall immunity and well-being.",
    ingredients: [
      "Somalata (Sarcostemma brevistigma) – Traditionally used to support respiratory comfort and healthy breathing.",
      "Mulethi (Licorice – Glycyrrhiza glabra) – Well known for its soothing effect on the throat and support for respiratory health.",
      "Gaozaban (Onosma bracteatum) – Traditionally valued for its cooling and calming properties that help promote respiratory wellness.",
      "Vasaka (Adhatoda vasica) – One of Ayurveda's most respected herbs for supporting bronchial health and maintaining clear airways.",
      "Kantakari (Solanum surattense) – Traditionally used to support healthy lung function and respiratory comfort.",
      "Saunf (Fennel – Foeniculum vulgare) – Helps soothe the throat and supports healthy digestion.",
      "Bharangi (Clerodendrum serratum) – Traditionally used to support healthy respiratory function.",
      "Bhringraj (Eclipta alba) – Known in Ayurveda for its rejuvenating and wellness-supporting properties.",
      "Tulsi (Holy Basil – Ocimum sanctum) – Rich in natural antioxidants and traditionally used to support immunity and respiratory health.",
      "Kakrasingi (Pistacia integerrima) – Traditionally valued for promoting respiratory comfort.",
      "Gul Banafsha (Viola odorata) – Traditionally used to soothe the throat and support healthy breathing.",
      "Draksha (Grapes – Vitis vinifera) – Rich in natural antioxidants that contribute to overall wellness.",
      "Nausar (Ammonium Chloride) – Traditionally included in cough formulations to help loosen mucus and support easier expectoration.",
      "Pippali (Long Pepper – Piper longum) – Supports respiratory health and helps enhance the absorption of herbal ingredients.",
      "Sunthi (Dry Ginger – Zingiber officinale) – Helps support healthy respiratory function and digestive wellness.",
      "Madhu (Honey) – Naturally soothes the throat while enhancing the taste of the formulation.",
      "Menthol – Provides a cooling sensation and helps promote a feeling of clear, comfortable breathing.",
    ],
    benefits: [
      "Supports respiratory wellness and healthy lung function",
      "Helps soothe throat irritation and promote throat comfort",
      "Supports healthy mucus clearance",
      "Promotes easier breathing and respiratory comfort",
      "Enriched with traditional Ayurvedic herbs and natural honey",
      "Suitable as a daily Ayurvedic herbal respiratory tonic when used as directed",
      "Traditionally supports bronchial health and seasonal respiratory wellness",
      "Traditionally supports general immunity and vitality",
    ],
    usage: "Adults: 2 teaspoonfuls three times daily with lukewarm water. Children: 1 teaspoonful twice daily, or as directed by a qualified healthcare professional.",
    image: "/images/kashMukti.webp",
    disclaimer: "KAS MUKTI is an Ayurvedic Proprietary Medicine. The benefits described are based on the traditional Ayurvedic uses of its individual herbal ingredients and are not intended to diagnose, treat, cure, or prevent any disease. Consult a qualified healthcare professional before use if you are pregnant, breastfeeding, have a medical condition, or are taking prescription medications.",
  },
  {
    id: "macordial",
    name: "M.A. CORDIAL – Ayurvedic Uterine Tonic",
    category: "syrups",
    shortDescription: "Traditional Ayurvedic Care for Women's Wellness",
    description: "M.A. CORDIAL is a carefully formulated Ayurvedic uterine tonic that combines renowned herbs, minerals, and traditional ingredients to support women's reproductive health, vitality, and overall well-being. Based on Ayurvedic principles, this tonic is designed to help maintain hormonal balance, promote uterine health, and support strength and energy.",
    ingredients: [
      "Ashoka (Saraca asoca) – One of Ayurveda's most respected herbs for supporting uterine health and maintaining menstrual comfort and balance.",
      "Ashwagandha (Withania somnifera) – A rejuvenating adaptogen traditionally used to promote energy, vitality, stamina, and resilience to everyday stress.",
      "Vidarikanda (Ipomoea digitata) – Traditionally valued as a nourishing herb that supports strength, vitality, and overall wellness.",
      "Majuphal (Quercus infectoria) – Traditionally used for its astringent properties to support female reproductive health.",
      "Kala Jeera (Carum bulbocastanum) – Supports healthy digestion and contributes to overall metabolic wellness.",
      "Nagarmotha (Cyperus rotundus) – Traditionally used to promote digestive comfort and help maintain hormonal balance.",
      "Sunthi (Dry Ginger) – Supports digestion, circulation, and healthy metabolism.",
      "Daruharidra (Berberis aristata) – Traditionally known for its antioxidant and wellness-supporting properties.",
      "Kamal (Lotus – Nelumbo nucifera) – Traditionally used to promote cooling, balance, and overall vitality.",
      "Haritaki (Terminalia chebula) – Supports digestive health and natural detoxification.",
      "Bibhitaki (Terminalia bellirica) – Traditionally used to support healthy metabolism and overall wellness.",
      "Amalaki (Emblica officinalis) – A rich natural source of antioxidants that supports immunity and rejuvenation.",
      "Jeera (Cuminum cyminum) – Helps support digestion and nutrient absorption.",
      "Adusa (Adhatoda vasica) – Traditionally valued for supporting respiratory and general wellness.",
      "Lal Chandan (Pterocarpus santalinus) – Traditionally used for its cooling and soothing properties.",
      "Trivang Bhasma – Traditionally used in Ayurvedic formulations to support women's reproductive and urinary health.",
      "Loh Bhasma (Ferrum Oxidum) – A traditional Ayurvedic iron preparation used to support healthy blood formation and energy levels.",
      "Muktasukti Bhasma – Traditionally valued for supporting calcium balance, vitality, and overall wellness.",
    ],
    benefits: [
      "Supports uterine and reproductive health",
      "Helps maintain menstrual comfort and hormonal balance",
      "Promotes vitality, strength, and overall wellness",
      "Supports healthy blood formation and energy",
      "Enriched with antioxidant-rich Ayurvedic herbs",
      "Made with a balanced blend of traditional herbs and mineral preparations",
      "Traditionally supports women's reproductive wellness",
      "Traditionally supports strength and overall feminine wellness",
    ],
    usage: "Take 10–15 ml two or three times daily with lukewarm water, or as directed by a qualified healthcare professional.",
    image: "/images/macordial.webp",
    disclaimer: "M.A. CORDIAL is an Ayurvedic Proprietary Medicine. The benefits described are based on the traditional Ayurvedic uses of its individual ingredients and are not intended to diagnose, treat, cure, or prevent any disease. Consult a qualified healthcare professional before use, especially during pregnancy, breastfeeding, or if you have an existing medical condition.",
  },
  {
    id: "ma-liver",
    name: "M.A. LIV – Herbal Liver Tonic",
    category: "formulations",
    shortDescription: "Ayurvedic Support for Liver Health & Daily Wellness",
    description: "M.A. LIV is a carefully formulated Ayurvedic liver tonic that combines traditional hepatoprotective herbs with antioxidant-rich botanicals to support healthy liver function, digestion, metabolism, and overall vitality. Its balanced herbal blend helps maintain the body's natural detoxification processes while promoting digestive comfort and general well-being.",
    ingredients: [
      "Kutki (Picrorhiza kurroa) – One of Ayurveda's most valued herbs for supporting healthy liver function and natural detoxification.",
      "Sharpunkha (Tephrosia purpurea) – Traditionally used to promote liver wellness and support healthy metabolism.",
      "Bhringraj (Eclipta alba) – A rejuvenating herb traditionally known to support liver health and overall vitality.",
      "Kakamachi (Solanum nigrum) – Traditionally used to support liver function and digestive wellness.",
      "Pitpapda (Oldenlandia herbacea) – Traditionally valued for supporting the body's natural cleansing processes.",
      "Kalmegh (Andrographis paniculata) – Known in Ayurveda for promoting healthy liver function, digestion, and immune support.",
      "Bhuiamla (Phyllanthus fraternus) – Traditionally used to help maintain liver health and support detoxification.",
      "Giloy (Tinospora cordifolia) – A renowned Ayurvedic herb that supports immunity, vitality, and overall wellness.",
      "Vasa (Adhatoda vasica) – Traditionally used to support respiratory and general health.",
      "Phalsa (Grewia asiatica) – Rich in natural antioxidants that contribute to overall wellness.",
      "Amalaki (Emblica officinalis) – A rich source of natural antioxidants that supports immunity and rejuvenation.",
      "Daruharidra (Berberis aristata) – Traditionally valued for supporting liver health and overall metabolic balance.",
      "Punarnava (Boerhavia diffusa) – Traditionally used to support kidney and liver function and help maintain healthy fluid balance.",
      "Sunthi (Dry Ginger – Zingiber officinale) – Promotes healthy digestion and supports metabolic function.",
      "Chitrak (Plumbago zeylanica) – Traditionally used to stimulate digestion and improve nutrient absorption.",
      "Lohasava – A classical Ayurvedic preparation traditionally used to support healthy blood formation, digestion, and vitality.",
    ],
    benefits: [
      "Supports healthy liver function and natural detoxification",
      "Promotes healthy digestion and metabolism",
      "Rich in antioxidant and rejuvenating Ayurvedic herbs",
      "Helps maintain appetite and digestive comfort",
      "Supports overall vitality and daily wellness",
      "Formulated using trusted Ayurvedic ingredients",
      "Traditionally supports healthy liver function and detoxification processes",
      "Traditionally supports metabolic balance and general vitality",
    ],
    usage: "Take 5–10 ml twice daily, or as directed by a qualified healthcare professional.",
    image: "/images/MALiver.webp",
    disclaimer: "M.A. LIV is an Ayurvedic Proprietary Medicine. The benefits described are based on the traditional Ayurvedic uses of its individual herbal ingredients and are not intended to diagnose, treat, cure, or prevent any disease. Consult a qualified healthcare professional before use if you are pregnant, breastfeeding, or have an existing medical condition.",
  },
  {
    id: "memo-brain",
    name: "MEMO BRAIN – Herbal Brain Tonic",
    category: "formulations",
    shortDescription: "Nourish Your Mind Naturally with Ayurvedic Wisdom",
    description: "MEMO BRAIN is an Ayurvedic herbal brain tonic formulated with time-honored herbs traditionally used to support memory, concentration, mental clarity, vitality, and overall nervous system health. Its carefully selected botanical ingredients help promote cognitive wellness while supporting the body's natural ability to cope with daily stress.",
    ingredients: [
      "Ajwain (Trachyspermum ammi) – Traditionally supports healthy digestion, helping improve nutrient absorption essential for overall wellness.",
      "Brahmi (Bacopa monnieri) – One of Ayurveda's most renowned herbs for supporting memory, learning, concentration, and cognitive function.",
      "Shankhpushpi (Convolvulus pluricaulis) – Traditionally used to promote mental calmness, focus, and memory.",
      "Ashwagandha (Withania somnifera) – An adaptogenic herb that helps support energy, vitality, stamina, and resistance to everyday stress.",
      "Tagar (Valeriana wallichii) – Traditionally valued for promoting relaxation and supporting healthy sleep.",
      "Jatamansi (Nardostachys jatamansi) – Supports mental relaxation, emotional balance, and cognitive wellness.",
      "Sarpagandha (Rauvolfia serpentina) – Traditionally used under professional guidance to support nervous system balance.",
      "Daruhaldi (Berberis aristata) – Traditionally used to support overall health through its antioxidant and wellness-promoting properties.",
      "Yashtimadhu (Licorice) – Traditionally valued for its rejuvenating properties and support for general vitality.",
      "Agar (Aquilaria agallocha) – An aromatic Ayurvedic herb traditionally used to promote calmness and mental well-being.",
    ],
    benefits: [
      "Supports memory and cognitive function",
      "Helps improve concentration and mental alertness",
      "Promotes a healthy nervous system",
      "Helps manage everyday stress and mental fatigue",
      "Supports vitality, stamina, and overall wellness",
      "Formulated with trusted Ayurvedic herbs for daily cognitive support",
      "Traditionally supports memory and learning",
      "Traditionally supports mental focus and concentration",
      "Traditionally supports energy and vitality",
    ],
    usage: "Take 2 teaspoonfuls three times daily with milk, or as directed by a qualified healthcare professional.",
    image: "/images/memo-brain.webp",
    disclaimer: "MEMO BRAIN is an Ayurvedic Proprietary Medicine. The benefits described are based on the traditional Ayurvedic uses of its herbal ingredients. This product is not intended to diagnose, treat, cure, or prevent any disease. Individuals with medical conditions, especially those taking medications for blood pressure or neurological conditions, should consult a healthcare professional before use.",
  },
  {
    id: "rakta-shodak",
    name: "M.A. RAKTA SHODHAK – Herbal Blood Purifier Tonic",
    category: "syrups",
    shortDescription: "Traditional Ayurvedic Support for Healthy Blood & Natural Wellness",
    description: "M.A. RAKTA SHODHAK is a thoughtfully formulated Ayurvedic blood purifier tonic made with a blend of time-honored herbs traditionally used to support healthy blood, natural detoxification, skin health, and overall vitality. Enriched with cooling and rejuvenating botanicals, it helps promote internal balance while supporting the body's natural cleansing processes.",
    ingredients: [
      "Shvet Sariva (Hemidesmus indicus) – One of Ayurveda's most respected blood-purifying herbs, traditionally used to support healthy skin and natural detoxification.",
      "Usva (Vetiver – Vetiveria zizanioides) – A cooling herb traditionally used to refresh the body and promote overall wellness.",
      "Manjistha (Rubia cordifolia) – Renowned in Ayurveda for supporting healthy blood circulation, skin health, and natural detoxification.",
      "Saunf (Fennel – Foeniculum vulgare) – Helps support healthy digestion and contributes to overall metabolic balance.",
      "Unnab (Ziziphus jujuba) – Traditionally valued for its nourishing and antioxidant properties that support general wellness.",
      "Sapistan (Cordia latifolia) – Traditionally used to promote respiratory comfort and overall body balance.",
      "Hansraj (Adiantum lunulatum) – Traditionally appreciated for supporting respiratory and general health.",
      "Gaozaban (Onosma bracteatum) – A cooling Ayurvedic herb traditionally used to promote vitality and internal balance.",
      "Mishri (Rock Sugar) – Traditionally added to improve palatability while providing a soothing effect.",
    ],
    benefits: [
      "Supports healthy blood and natural purification*",
      "Helps maintain healthy, radiant skin*",
      "Promotes the body's natural detoxification processes*",
      "Supports digestive wellness and overall metabolism*",
      "Enriched with antioxidant-rich Ayurvedic herbs*",
      "Provides cooling and rejuvenating herbal support for daily wellness*",
    ],
    usage: "Adults: 10–20 ml two or three times daily with water, or as directed by a qualified healthcare professional. Children: ½–1 teaspoonful three times daily with water, or as directed by a qualified healthcare professional.",
    image: "/images/RaktaShodak.webp",
    disclaimer: "M.A. RAKTA SHODHAK is an Ayurvedic Proprietary Medicine. The benefits described are based on the traditional Ayurvedic uses of its individual ingredients and are not intended to diagnose, treat, cure, or prevent any disease. Consult a qualified healthcare professional before use if you are pregnant, breastfeeding, have an existing medical condition, or are taking prescription medications.",
  },
  {
    id: "zyme",
    name: "M.A. ZYME – Herbal Tonic Enzyme Syrup",
    category: "formulations",
    shortDescription: "Nature's Ayurvedic Blend for Everyday Digestive Wellness",
    description: "M.A. ZYME is a thoughtfully formulated Ayurvedic herbal tonic that combines traditional digestive herbs, fruits, aromatic spices, and natural honey to help support healthy digestion, appetite, and overall well-being.",
    ingredients: [
      "Jeera (Cuminum cyminum) – Traditionally used to support digestion and reduce bloating.",
      "Sunthi (Dry Ginger) – Helps promote digestive comfort and healthy metabolism.",
      "Kali Maricha (Black Pepper) – Supports digestion and enhances the absorption of herbal nutrients.",
      "Pippali (Long Pepper) – Traditionally valued for supporting digestive and respiratory health.",
      "Haritaki – A renowned Ayurvedic herb that supports gut health and regular bowel function.",
      "Bibhitaki – Traditionally used to support healthy digestion and detoxification.",
      "Amalaki (Indian Gooseberry) – Rich in natural antioxidants and traditionally used to promote vitality and immunity.",
      "Apple (Pyrus malus) – Provides natural fruit nutrients that complement digestive wellness.",
      "Orange (Citrus sinensis) – A natural source of vitamin C and refreshing fruit compounds.",
      "Grapes (Vitis vinifera) – Rich in antioxidants that support general wellness.",
      "Pear (Pyrus communis) – Traditionally appreciated for its gentle digestive properties.",
      "Tejpatra (Cinnamomum tamala) – Aromatic herb traditionally used to aid digestion.",
      "Nagkesar (Mesua ferrea) – Valued in Ayurveda for supporting overall health and balance.",
      "Cardamom (Elettaria cardamomum) – Helps freshen the breath and promotes digestive comfort.",
      "Cinnamon (Cinnamomum zeylanicum) – Traditionally used to support healthy digestion and metabolism.",
      "Honey (Madhu) – A natural ingredient that enhances taste while traditionally supporting overall wellness.",
      "Dhataki (Woodfordia fruticosa) – An important Ayurvedic ingredient commonly used in traditional herbal formulations.",
    ],
    benefits: [
      "Supports healthy digestion and appetite",
      "Helps promote digestive comfort",
      "Enriched with traditional Ayurvedic herbs and fruits",
      "Contains natural antioxidants from herbal and fruit ingredients",
      "Suitable as a daily Ayurvedic digestive tonic when used as directed",
    ],
    usage: "Take as directed by your physician or healthcare professional.",
    image: "/images/zyme.jpeg",
    disclaimer: "M.A. ZYME is an Ayurvedic proprietary medicine. The benefits described are based on the traditional uses of its individual herbal ingredients and are not intended to diagnose, treat, cure, or prevent any disease.",
  },

  {
    id: "charcoal-herbal-soap",
    name: "Charcoal Herbal Soap",
    category: "cosmetics",
    shortDescription: "Handmade premium charcoal soap for deep cleansing and detoxification",
    description: "Our premium Charcoal Herbal Soap is handcrafted using activated charcoal and natural herbs. This luxurious soap provides deep cleansing, removes impurities, and detoxifies the skin naturally. Perfect for all skin types, especially oily and acne-prone skin.",
    ingredients: ["Activated Charcoal", "Natural Herbs", "Coconut Oil", "Palm Oil", "Glycerin"],
    benefits: [
      "Deep cleansing and detoxification",
      "Removes excess oil and impurities",
      "Natural antibacterial properties",
      "Suitable for all skin types",
      "Handmade with premium ingredients",
    ],
    usage: "Wet the soap and create a rich lather. Gently massage onto wet skin and rinse thoroughly with water. Use daily for best results.",
    image: "/images/4ca8eb_6f91b78b57fb48d2b68edcee16f86331~mv2 (1).jpeg",
  },
  {
    id: "almond-body-butter",
    name: "Almond Body Butter",
    category: "cosmetics",
    shortDescription: "Nourishing almond body butter for soft and supple skin",
    description: "Luxurious Almond Body Butter enriched with pure almond oil and natural moisturizers. This rich, creamy formula deeply moisturizes the skin, provides long-lasting hydration, and leaves skin feeling soft, smooth, and beautifully fragrant.",
    ingredients: ["Sweet Almond Oil", "Shea Butter", "Cocoa Butter", "Vitamin E", "Natural Fragrance"],
    benefits: [
      "Makes skin soft and supple",
      "Deeply moisturizes the skin",
      "Provides long-lasting hydration",
      "Improves skin texture",
      "Natural nourishment",
    ],
    usage: "Apply generously to clean, dry skin. Massage gently until fully absorbed. Use daily for best results, especially after bathing.",
    image: "/images/almond-body-butter.png",
  },
  {
    id: "immunity-booster-syrup",
    name: "Immunity Booster Syrup",
    category: "syrups",
    shortDescription: "Ayurvedic immunity booster syrup for energy, immunity and performance",
    description: "Our Immunity Booster Syrup is a powerful Ayurvedic formulation designed to enhance your body's natural defense system. This comprehensive health tonic boosts energy levels, strengthens immunity, and improves overall performance naturally.",
    ingredients: ["Amla", "Giloy", "Tulsi", "Ashwagandha", "Honey", "Natural Herbs"],
    benefits: [
      "Helpful in treating energy deficiency",
      "Boosts natural immunity",
      "Enhances physical performance",
      "Supports overall health",
      "Natural Ayurvedic formulation",
    ],
    usage: "Take 10-15ml twice daily with water or as directed by healthcare practitioner. Best taken on empty stomach for optimal absorption.",
    image: "/images/4ca8eb_8d8658451a794285a2c7adeb2a24d914~mv2 (1).jpeg",
  },



  {
    id: "tulsi-dried",
    name: "Organic Tulsi Leaves",
    category: "herbs",
    shortDescription: "Holy Basil leaves for respiratory and immune support",
    description: "Sacred Tulsi (Holy Basil) leaves, carefully harvested and dried to preserve essential oils and therapeutic compounds. Known as the 'Queen of Herbs' in Ayurveda.",
    ingredients: ["100% Organic Tulsi Leaves (Ocimum sanctum)"],
    benefits: [
      "Supports respiratory health",
      "Immune system support",
      "Adaptogenic properties",
      "Promotes clear breathing",
      "Antioxidant rich",
    ],
    usage: "Steep 1 teaspoon in hot water for 5-10 minutes for tea. Can also be used in cooking or as directed.",
    image: "/images/tulsi.jpg",
  },
  {
    id: "neem-powder",
    name: "Neem Leaf Powder",
    category: "powders",
    shortDescription: "Blood purifying and skin supporting herbal powder",
    description: "Pure Neem leaf powder from sustainably sourced Azadirachta indica trees. Known for its powerful purifying and skin-supporting properties in traditional Ayurvedic practice.",
    ingredients: ["100% Organic Neem Leaves (Azadirachta indica)"],
    benefits: [
      "Supports healthy skin",
      "Blood purification",
      "Natural antimicrobial",
      "Supports oral health",
      "Balances Pitta and Kapha",
    ],
    usage: "Mix 1/4 to 1/2 teaspoon with water or honey. Can also be used topically as a paste.",
    image: "/images/neem.jpg",
  },
  {
    id: "sesame-oil",
    name: "Organic Sesame Oil",
    category: "oils",
    shortDescription: "Cold-pressed sesame oil for Abhyanga massage",
    description: "Premium cold-pressed sesame oil, the traditional base oil for Ayurvedic body massage (Abhyanga). Rich in antioxidants and deeply nourishing for all skin types.",
    ingredients: ["100% Cold-pressed Organic Sesame Oil"],
    benefits: [
      "Deep tissue nourishment",
      "Supports joint flexibility",
      "Warming and grounding",
      "Balances Vata dosha",
      "Traditional massage oil",
    ],
    usage: "Warm before use. Apply generously for full body massage. Allow to absorb for 15-20 minutes before bathing.",
    image: "/images/sesame-oil.jpg",
  },
];

export const certifications = [
  { name: "GMP Certified", description: "Good Manufacturing Practice" },
  { name: "ISO 22000", description: "Food Safety Management" },
];

export const whyChooseUs = [
  {
    title: "Premium Quality",
    description: "Sourced from trusted farms and processed in state-of-the-art facilities with strict quality control.",
    icon: "shield-check",
  },
  {
    title: "Sustainable Practices",
    description: "Committed to ethical sourcing, fair trade, and environmentally responsible manufacturing.",
    icon: "leaf",
  },
  {
    title: "Global Export",
    description: "Serving partners in 50+ countries with reliable logistics and documentation support.",
    icon: "globe",
  },
];
